In [ ]:
import numpy as np

In [ ]:
array_list=[120,30,40,50,60]
array=np.array(array_list)
print(array_list)
print(array)

[120, 30, 40, 50, 60]
[120  30  40  50  60]


In [ ]:
matrix = np.array([
    [25,30,80],
    [40,60,90],
    [25,50,65]
])
print(matrix)


[[25 30 80]
 [40 60 90]
 [25 50 65]]


In [ ]:
zero_matrix=np.zeros((4,5))
sequenced_matrix= np.arange(0,11,2)
print(zero_matrix)
print(sequenced_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[ 0  2  4  6  8 10]


In [ ]:
traffic = np.array((60,20,80,20,40))


In [ ]:
weeekend_traffic = traffic[:-3:]
print(weeekend_traffic)

[60 20]


In [ ]:
sensors = np.array([
    [20,30,40],
    [40,60,20]
])