<a href="https://colab.research.google.com/github/bishalkshah70-art/AI-and-Ml-/blob/main/day1_numpy_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
sales_list = [120,150,300,250,90]
sales_array=np.array(sales_list)
print(sales_list)
print(sales_array)


[120, 150, 300, 250, 90]
[120 150 300 250  90]


In [ ]:
customer_matrix=np.array([
    [25,50,710],
    [41,95,700],
    [32,65,620]
])
print(customer_matrix)

[[ 25  50 710]
 [ 41  95 700]
 [ 32  65 620]]


In [ ]:
zero_matrix=np.zeros((3, 4))
sequenced_matrix= np.arange(0,10,2)
print(zero_matrix)
print(sequenced_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 2 4 6 8]


In [ ]:
traffic = np.array((500,620,480,710,911,1100))

In [ ]:
weekend_traffic = traffic[-2:]
print(weekend_traffic)

[ 911 1000]


In [ ]:
a=[2,3,4,5,6,7]
print(a[-4:-1])

[4, 5, 6]


In [ ]:
sensors = np.array([
    [12.1,14,3,14,2],
    [10.5,11,2,11,9],
    [14.2,19,1,20,3],
    [18.5,19,1,20,3]
])

In [ ]:
specific_reading=sensors[2,1]
print(specific_reading)

19.0


In [ ]:
top_sensors = sensors[0:2,:]
print(top_sensors)

[[12.1 14.   3.  14.   2. ]
 [10.5 11.   2.  11.   9. ]]


In [ ]:
final_reading=sensors[:,2]
print(final_reading)

[3. 2. 1. 1.]


In [ ]:
flat_temps=np.array([22,24,35,23,45,34,23,44,23,34,26,24])

structred_temps = flat_temps.reshape(4,3)
print(structred_temps)

[[22 24 35]
 [23 45 34]
 [23 44 23]
 [34 26 24]]


In [ ]:
frahanite_temp = (structred_temps*9/5)+32
print(frahanite_temp)

[[ 71.6  75.2  95. ]
 [ 73.4 113.   93.2]
 [ 73.4 111.2  73.4]
 [ 93.2  78.8  75.2]]


In [ ]:
scores =np.array([
    [80,20,30],
    [50,60,60],
    [20,30,50]
])

print(np.max(scores))

80


In [ ]:
print( np.min (scores))

20


In [ ]:
print(np.mean(scores))

44.44444444444444


In [ ]:
subect_average= np.mean(scores,axis=0)
print(subect_average.round(2))

[50.   36.67 46.67]


In [ ]:
student_averages=np.mean(scores,axis=1)
print(student_averages)

[43.33333333 56.66666667 33.33333333]


In [ ]:
import time
size = 1_000_000
python_list= list(range(size))
numpy_array=np.arange(size)

In [ ]:
start_time=time.time()
python_list_result=[x*2 for x in python_list]
python_duration= time.time()-start_time

In [ ]:
start_time=time.time()
numpy_array_result=numpy_array*2
numpy_duration = time.time()-start_time

In [ ]:
print(f"time traken by standard pyrhon list:{python_duration:.5f} seconds")
print(f"time traken by numpy array:{numpy_duration:.5f} seconds")
print(f"numpy is roughly:{round (python_duration/numpy_duration)} x faster!")

time traken by standard pyrhon list:0.08140 seconds
time traken by numpy array:0.00461 seconds
numpy is roughly:18 x faster!
