In [ ]:
import numpy as np
from scipy import stats

In [ ]:
rent_prices = np.array([1200, 1350, 1200, 1400, 1550, 1300,1200, 12000])

In [ ]:
# calculating central tedenncy
mean_rent=np.mean(rent_prices)
median_rent=np.median(rent_prices)

In [ ]:
mode_result=stats.mode(rent_prices, keepdims=True)
print(mode_result)
mode_rent=mode_result.mode[0]
mode_count=mode_result.count[0]


ModeResult(mode=array([1200]), count=array([3]))


In [ ]:
print(f"Mean Rent: ${mean_rent}")
print(f"Median Rent: ${median_rent}")
print(f"Mode Rent: ${mode_rent}")

Mean Rent: $2650.0
Median Rent: $1325.0
Mode Rent: $1200


In [ ]:
# Dataset Daily tempratures for two cities over 5 day(Both have a mean of 25c)
city_a_temps=np.array([24,25,26,25,25])
city_b_temps=np.array([10,40,5,45,25])

var_a=np.var(city_a_temps)
var_b=np.var(city_b_temps)

In [ ]:
std_a=np.std(city_a_temps)
std_b=np.std(city_b_temps)
print(f"Variance in City A: {var_a: 2f}")
print(f"Variance in City B: {var_b: 2f}")
print(f"Standard Deviation in City A: {std_a: 2f}")
print(f"Standard Deviation in City B: {std_b: 2f}")

Variance in City A:  0.400000
Variance in City B:  250.000000
Standard Deviation in City A:  0.632456
Standard Deviation in City B:  15.811388


In [ ]:
# vraiables: making spend ($), Online Sales($) , and store complaints(count)
marketing_spend = np.array([10,20,30,40,50])
online_sales = np.array([25, 45, 55, 75, 95])
complaints = np.array([15,12,10,4,2])

In [ ]:
cov_matrix = np.cov(marketing_spend, online_sales)
cov_matrix1 = np.cov(marketing_spend, complaints)
print(cov_matrix)
print(cov_matrix1)


[[250. 425.]
 [425. 730.]]
[[250.  -85. ]
 [-85.   29.8]]


In [ ]:
corr_matrix_positive=np.corrcoef(marketing_spend, online_sales)
corr_matrix_negative=np.corrcoef(marketing_spend, complaints)
print(corr_matrix_positive)
print(corr_matrix_negative)


[[1.         0.99484975]
 [0.99484975 1.        ]]
[[ 1.         -0.98478356]
 [-0.98478356  1.        ]]


In [ ]:
correlation_spend_sales = np.corrcoef(marketing_spend, online_sales)[0, 1]
correlation_spend_complaints = np.corrcoef(marketing_spend, complaints)[0, 1]

print(f"Correlation between Marketing Spend and Online Sales: {correlation_spend_sales}")
print(f"Correlation between Marketing Spend and Complaints: {correlation_spend_complaints}")

Correlation between Marketing Spend and Online Sales: 0.9948497511671098
Correlation between Marketing Spend and Complaints: -0.9847835588179368
